# Generated by Django 5.2 on 2026-05-15 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlturadoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(verbose_name='Altura')),
            ],
            options={
                'verbose_name': 'Altura de Corte',
                'verbose_name_plural': 'Alturas de Corte',
            },
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('porcentagem', models.FloatField(verbose_name='Porcentagem (%)')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
            },
        ),
        migrations.CreateModel(
            name='EstadodeMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_movimento', models.BooleanField(default=False, verbose_name='Em Movimento')),
                ('velocidade', models.FloatField(verbose_name='Velocidade (km/h)')),
            ],
            options={
                'verbose_name': 'Estado de Movimento',
                'verbose_name_plural': 'Estados de Movimento',
            },
        ),
        migrations.CreateModel(
            name='LeituraTelemetria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maquina_id', models.CharField(max_length=50, verbose_name='ID da Máquina')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('vibracao', models.FloatField(verbose_name='Vibração')),
                ('rpm', models.IntegerField(verbose_name='RPM')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp do Sensor')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Leitura de Telemetria',
                'verbose_name_plural': 'Leituras de Telemetria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tempo_de_servico', models.IntegerField(verbose_name='Tempo de Serviço (anos)')),
                ('no_banco', models.BooleanField(default=True, verbose_name='No Banco')),
            ],
            options={
                'verbose_name': 'Operário',
                'verbose_name_plural': 'Operários',
            },
        ),
        migrations.CreateModel(
            name='PressaodoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao', models.FloatField(verbose_name='Pressão')),
            ],
            options={
                'verbose_name': 'Pressão de Corte',
                'verbose_name_plural': 'Pressões de Corte',
            },
        ),
        migrations.CreateModel(
            name='PressaoPneus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao', models.FloatField(verbose_name='Pressão')),
            ],
            options={
                'verbose_name': 'Pressão dos Pneus',
                'verbose_name_plural': 'Pressões dos Pneus',
            },
        ),
        migrations.CreateModel(
            name='StatusdeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_operacao', models.BooleanField(default=False, verbose_name='Em Operação')),
                ('tempo_de_operacao', models.FloatField(verbose_name='Tempo de Operação (h)')),
            ],
            options={
                'verbose_name': 'Status de Operação',
                'verbose_name_plural': 'Status de Operação',
            },
        ),
        migrations.CreateModel(
            name='TelemetriaInvalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_raw', models.TextField(help_text='JSON original, truncado em 2000 chars', verbose_name='Payload Bruto')),
                ('motivo_rejeicao', models.CharField(max_length=500, verbose_name='Motivo da Rejeição')),
                ('maquina_id', models.CharField(db_index=True, default='desconhecida', max_length=50, verbose_name='ID da Máquina')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Telemetria Inválida',
                'verbose_name_plural': 'Telemetrias Inválidas',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='TempUmi_Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('umidade', models.FloatField(verbose_name='Umidade (%)')),
            ],
            options={
                'verbose_name': 'Temperatura e Umidade do Ambiente',
                'verbose_name_plural': 'Temperaturas e Umidades do Ambiente',
            },
        ),
        migrations.CreateModel(
            name='UnidadedeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='TemperaturaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.modelo', verbose_name='Modelo da Máquina')),
            ],
            options={
                'verbose_name': 'Temperatura da Máquina',
                'verbose_name_plural': 'Temperaturas das Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Colheitadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_do_corte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.alturadocorte', verbose_name='Altura de Corte')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.combustivel', verbose_name='Combustível')),
                ('estado_de_movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.estadodemovimento', verbose_name='Estado de Movimento')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.modelo', verbose_name='Modelo')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.operario', verbose_name='Operário')),
                ('pressao_do_corte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.pressaodocorte', verbose_name='Pressão de Corte')),
                ('pressao_pneus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.pressaopneus', verbose_name='Pressão dos Pneus')),
                ('status_de_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.statusdeoperacao', verbose_name='Status de Operação')),
                ('temperatura_maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.temperaturamaquina', verbose_name='Temperatura da Máquina')),
                ('temp_umi_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.tempumi_ambiente', verbose_name='Temp./Umidade Ambiente')),
            ],
            options={
                'verbose_name': 'Colheitadeira',
                'verbose_name_plural': 'Colheitadeiras',
            },
        ),
        migrations.CreateModel(
            name='Transbordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.FloatField(verbose_name='Capacidade')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Transbordo',
                'verbose_name_plural': 'Transbordos',
            },
        ),
        migrations.AddField(
            model_name='pressaopneus',
            name='unidade_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='pressaodocorte',
            name='unidade_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='alturadocorte',
            name='unidade_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
    ]
