# Generated by Django 5.2 on 2026-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina_id', models.CharField(db_index=True, max_length=50, verbose_name='ID da Máquina')),
                ('prescricao', models.TextField(verbose_name='Prescrição')),
                ('acao_recomendada', models.CharField(max_length=500, verbose_name='Ação Recomendada')),
                ('severidade', models.CharField(choices=[('NORMAL', 'Normal'), ('ATENCAO', 'Atenção'), ('CRITICO', 'Crítico')], max_length=20, verbose_name='Severidade')),
                ('confianca', models.FloatField(verbose_name='Confiança (0.0 a 1.0)')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Gerado em')),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['-gerado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='leituratelemetria',
            index=models.Index(fields=['maquina_id', '-timestamp'], name='api_tcc_lei_maquina_97fc14_idx'),
        ),
        migrations.AddIndex(
            model_name='prescricao',
            index=models.Index(fields=['maquina_id', '-gerado_em'], name='api_tcc_pre_maquina_3d6639_idx'),
        ),
    ]
