# Generated by Django 5.2 on 2026-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0002_prescricao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescricao',
        ),
        migrations.RemoveIndex(
            model_name='leituratelemetria',
            name='api_tcc_lei_maquina_97fc14_idx',
        ),
        migrations.AddField(
            model_name='leituratelemetria',
            name='seq_id',
            field=models.BigIntegerField(editable=False, null=True, unique=True, verbose_name='ID Sequencial'),
        ),
    ]
