# Generated by Django 5.2 on 2026-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0005_colheitadeira_maquina_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheitadeira',
            name='maquina_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID da Máquina (Telemetria)'),
        ),
    ]
