# Generated by Django 5.2 on 2026-06-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0006_alter_colheitadeira_maquina_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='colheitadeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.colheitadeira', verbose_name='Colheitadeira'),
        ),
    ]
