# Generated by Django 5.2 on 2026-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0007_alter_prescricao_colheitadeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheitadeira',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativa'),
        ),
        migrations.AddIndex(
            model_name='leituratelemetria',
            index=models.Index(fields=['maquina_id', '-timestamp'], name='api_tcc_lei_maquina_97fc14_idx'),
        ),
    ]
