# Generated by Django 5.2 on 2026-08-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0008_colheitadeira_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leituratelemetria',
            name='seq_id',
        ),
    ]
