# Generated by Django 5.2 on 2026-08-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0009_remove_leituratelemetria_seq_id'),
    ]

    operations = [
    ]
