# Generated by Django 5.2 on 2026-08-21 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0010_protect_relacoes_criticas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAnalise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maquina_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('motivos', models.JSONField(default=list)),
                ('metricas', models.JSONField(default=dict)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['maquina_id', 'criado_em'], name='api_tcc_reg_maquina_61496d_idx')],
            },
        ),
    ]
