# Generated by Django 6.0.7 on 2026-09-04 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0011_registroanalise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_code', models.CharField(db_index=True, help_text='ID do hardware/ESP32 normalizado (.strip().upper())', max_length=100, unique=True, verbose_name='Código externo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('colheitadeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_tcc.colheitadeira', verbose_name='Colheitadeira vinculada')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_tcc.modelo', verbose_name='Modelo')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api_tcc.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['external_code'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Membro'), ('viewer', 'Visualizador')], default='member', max_length=50, verbose_name='Papel')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
