FROM node:22-alpine AS base

WORKDIR /app

COPY frontend-next/package*.json ./
RUN npm install --legacy-peer-deps

FROM base AS deps
COPY frontend-next/ ./
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/.next/standalone ./
COPY --from=deps /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
